# Generated by Django 3.2.9 on 2021-11-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter player's name", max_length=100)),
                ('team', models.CharField(help_text="Enter player's team", max_length=100)),
                ('nation', models.CharField(help_text="Enter player's nation", max_length=100)),
            ],
        ),
    ]
